import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import {
  Container,
  Flex,
  Heading,
  Stack,
  Text,
  Button,
  Icon,
  IconProps,
} from "@chakra-ui/react";
import UserProfileCard from "../components/UserProfileCard";
import NavMenu from "../components/NavMenu";

const Home: NextPage = () => {
  return (
    <div className="padding: 0px">
      <Head>
        <title>The Art Clique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://js.stripe.com/v3/"></script>
      </Head>

      {/* <UserProfileCard /> */}
      <Container
        maxW="100%"
        h="calc(100vh)"
        bgGradient="linear(to-b, #181820, #0b0b0f)"
      >
        <Navbar />
        <Container maxW={"5xl"}>
          <Stack
            textAlign={"center"}
            align={"center"}
            spacing={{ base: 8, md: 10 }}
            py={{ base: 20, md: 24 }}
          >
            <Heading
              fontWeight={600}
              fontSize={{ base: "3xl", sm: "4xl", md: "6xl" }}
              lineHeight={"110%"}
              color="white"
            >
              Welcome to {" "}
              <Text
                as={"span"}
                bgGradient="linear(to-r, blue.500, purple.500)"
                bgClip="text"
              >
                The Art Clique
              </Text>
            </Heading>
            <Text color={"gray.500"} maxW={"3xl"}>
              Never miss a meeting. Never be late for one too. Keep track of
              your meetings and receive smart reminders in appropriate times.
              Read your smart “Daily Agenda” every morning.
            </Text>
            <Stack spacing={6} direction={"row"}>
              <Button
                as={"a"}
                width={"60%"}
                href={"register"}
                rounded={"full"}
                px={6}
                bgGradient="linear(to-r, blue.500, purple.500)"
                color={"white"}
                _hover={{
                  bgGradient: "linear(to-r, blue.400, purple.400)",
                  shadow: "white_btn",
                }}
              >
                Register Now
              </Button>
              <Button
                as={"a"}
                href={"login"}
                width={"50%"}
                rounded={"full"}
                px={6}
                _hover={{
                  shadow: "white_btn",
                }}
              >
                Log In
              </Button>
            </Stack>
            <Flex w={"full"}>
              {/* <Illustration
            height={{ sm: '24rem', lg: '28rem' }}
            mt={{ base: 12, sm: 16 }}
          /> */}
            </Flex>
          </Stack>
        </Container>
      </Container>
    </div>
  );
};

export default Home;
